/*
 * GoCardless Bank Account Data API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0 (v2)
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AccountDetailSchema {
    #[serde(rename = "account")]
    pub account: Box<crate::models::DetailSchema>,
}

impl AccountDetailSchema {
    pub fn new(account: crate::models::DetailSchema) -> AccountDetailSchema {
        AccountDetailSchema {
            account: Box::new(account),
        }
    }
}


