/*
 * GoCardless Bank Account Data API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0 (v2)
 * 
 * Generated by: https://openapi-generator.tech
 */


#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct BankTransactions {
    pub transactions: BankTransactionStatusSchema,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct BankTransactionStatusSchema {
    #[serde(rename = "booked")]
    pub booked: Vec<crate::models::TransactionSchema>,
    #[serde(rename = "pending", skip_serializing_if = "Option::is_none")]
    pub pending: Option<Vec<crate::models::TransactionSchema>>,
}

impl BankTransactionStatusSchema {
    pub fn new(booked: Vec<crate::models::TransactionSchema>) -> BankTransactionStatusSchema {
        BankTransactionStatusSchema {
            booked,
            pending: None,
        }
    }
}


