/*
 * GoCardless Bank Account Data API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0 (v2)
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct MinimumRequiredFields {
    #[serde(rename = "single-payment")]
    pub single_payment: Box<crate::models::SinglePayment>,
}

impl MinimumRequiredFields {
    pub fn new(single_payment: crate::models::SinglePayment) -> MinimumRequiredFields {
        MinimumRequiredFields {
            single_payment: Box::new(single_payment),
        }
    }
}


