/*
 * GoCardless Bank Account Data API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0 (v2)
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct PaymentDeleted {
    #[serde(rename = "summary")]
    pub summary: String,
    #[serde(rename = "detail")]
    pub detail: String,
}

impl PaymentDeleted {
    pub fn new(summary: String, detail: String) -> PaymentDeleted {
        PaymentDeleted {
            summary,
            detail,
        }
    }
}


