/*
 * GoCardless Bank Account Data API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0 (v2)
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SinglePayment {
    #[serde(rename = "T2P")]
    pub t2_p: Box<crate::models::T2P>,
    #[serde(rename = "SCT")]
    pub sct: Box<crate::models::Sct>,
    #[serde(rename = "ISCT")]
    pub isct: Box<crate::models::Isct>,
    #[serde(rename = "CBCT")]
    pub cbct: Box<crate::models::Cbct>,
    #[serde(rename = "BACS")]
    pub bacs: Box<crate::models::Bacs>,
    #[serde(rename = "CHAPS")]
    pub chaps: Box<crate::models::Chaps>,
    #[serde(rename = "FPS")]
    pub fps: Box<crate::models::Fps>,
    #[serde(rename = "SWIFT")]
    pub swift: Box<crate::models::Swift>,
    #[serde(rename = "BT")]
    pub bt: Box<crate::models::Bt>,
    #[serde(rename = "MT")]
    pub mt: Box<crate::models::Mt>,
    #[serde(rename = "DCT")]
    pub dct: Box<crate::models::Dct>,
    #[serde(rename = "IDCT")]
    pub idct: Box<crate::models::Idct>,
}

impl SinglePayment {
    pub fn new(t2_p: crate::models::T2P, sct: crate::models::Sct, isct: crate::models::Isct, cbct: crate::models::Cbct, bacs: crate::models::Bacs, chaps: crate::models::Chaps, fps: crate::models::Fps, swift: crate::models::Swift, bt: crate::models::Bt, mt: crate::models::Mt, dct: crate::models::Dct, idct: crate::models::Idct) -> SinglePayment {
        SinglePayment {
            t2_p: Box::new(t2_p),
            sct: Box::new(sct),
            isct: Box::new(isct),
            cbct: Box::new(cbct),
            bacs: Box::new(bacs),
            chaps: Box::new(chaps),
            fps: Box::new(fps),
            swift: Box::new(swift),
            bt: Box::new(bt),
            mt: Box::new(mt),
            dct: Box::new(dct),
            idct: Box::new(idct),
        }
    }
}


